/*
          # [Operation Name]
          Create Campaigns Schema

          [Description of what this operation does]
          This script sets up the necessary database schema for managing marketing campaigns. It creates the 'campaigns' table to store campaign details, a 'campaign_leads' join table to associate leads with campaigns, and a function to retrieve campaign data efficiently.

          ## Query Description: [This operation will add new tables and functions to your database to support campaign functionality. It is a non-destructive operation and will not affect any existing data in other tables. No backups are required before running this script, as it only introduces new structures.]
          
          ## Metadata:
          - Schema-Category: "Structural"
          - Impact-Level: "Low"
          - Requires-Backup: false
          - Reversible: true
          
          ## Structure Details:
          - Tables Created: `public.campaigns`, `public.campaign_leads`
          - Types Created: `public.campaign_status`
          - Functions Created: `public.get_campaigns_with_lead_count`, `public.populate_campaign_lead_user_id`
          - Triggers Created: `before_insert_campaign_lead` on `public.campaign_leads`
          
          ## Security Implications:
          - RLS Status: Enabled on new tables.
          - Policy Changes: Yes, new policies are created for `campaigns` and `campaign_leads` to ensure users can only access their own data.
          - Auth Requirements: Policies are based on `auth.uid()`.
          
          ## Performance Impact:
          - Indexes: Primary keys and foreign keys are indexed automatically.
          - Triggers: A trigger is added to `campaign_leads` to automatically populate the `user_id`, ensuring data integrity for RLS policies.
          - Estimated Impact: Low. The new structures are optimized for the application's query patterns.
          */

-- Create a custom type for campaign status for better data integrity.
CREATE TYPE public.campaign_status AS ENUM ('Draft', 'Active', 'Paused', 'Completed');

-- Create the main 'campaigns' table to store campaign configurations.
CREATE TABLE public.campaigns (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    name text NOT NULL,
    agent_id uuid NOT NULL,
    schedule jsonb NOT NULL,
    pacing jsonb NOT NULL,
    retry_rules jsonb NOT NULL,
    status public.campaign_status NOT NULL DEFAULT 'Draft'::public.campaign_status,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT campaigns_pkey PRIMARY KEY (id),
    CONSTRAINT campaigns_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(id) ON DELETE RESTRICT,
    CONSTRAINT campaigns_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.campaigns IS 'Stores campaign configurations for outbound calling.';

-- Enable Row Level Security and define policies for the 'campaigns' table.
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own campaigns" ON public.campaigns FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Create the 'campaign_leads' join table to link campaigns with their leads.
CREATE TABLE public.campaign_leads (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    campaign_id uuid NOT NULL,
    lead_id uuid NOT NULL,
    user_id uuid NOT NULL,
    status text NOT NULL DEFAULT 'Queued'::text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT campaign_leads_pkey PRIMARY KEY (id),
    CONSTRAINT campaign_leads_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE,
    CONSTRAINT campaign_leads_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id) ON DELETE CASCADE,
    CONSTRAINT campaign_leads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT campaign_leads_campaign_id_lead_id_key UNIQUE (campaign_id, lead_id)
);
COMMENT ON TABLE public.campaign_leads IS 'Join table linking campaigns to their respective leads.';

-- Enable Row Level Security and define policies for the 'campaign_leads' table.
ALTER TABLE public.campaign_leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own campaign leads" ON public.campaign_leads FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Create a trigger function to automatically populate the user_id in campaign_leads
-- This ensures RLS works correctly without changing the frontend code.
CREATE OR REPLACE FUNCTION public.populate_campaign_lead_user_id()
RETURNS TRIGGER AS $$
DECLARE
    v_user_id uuid;
BEGIN
    SELECT user_id INTO v_user_id FROM public.campaigns WHERE id = NEW.campaign_id;
    NEW.user_id := v_user_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create the trigger that uses the function above.
CREATE TRIGGER before_insert_campaign_lead
BEFORE INSERT ON public.campaign_leads
FOR EACH ROW
EXECUTE FUNCTION public.populate_campaign_lead_user_id();

-- Create the RPC function required by the dashboard to get campaigns with their lead counts.
CREATE OR REPLACE FUNCTION public.get_campaigns_with_lead_count(p_user_id uuid)
RETURNS TABLE(id uuid, name text, status public.campaign_status, created_at timestamptz, agents json, lead_count bigint)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    SELECT
        c.id,
        c.name,
        c.status,
        c.created_at,
        json_build_object('name', a.name) as agents,
        count(cl.lead_id) as lead_count
    FROM
        public.campaigns c
    LEFT JOIN
        public.agents a ON c.agent_id = a.id
    LEFT JOIN
        public.campaign_leads cl ON c.id = cl.campaign_id
    WHERE
        c.user_id = p_user_id
    GROUP BY
        c.id, a.name
    ORDER BY
        c.created_at DESC;
END;
$$;

-- Grant execution rights on the function to authenticated users.
GRANT EXECUTE ON FUNCTION public.get_campaigns_with_lead_count(uuid) TO authenticated;
